from __future__ import annotations

import streamlit as st

from src.config.settings import Settings
from src.database.db import get_connection
from src.guardrails.language_filters import BANNED_PATTERNS
from src.guardrails.source_hierarchy import AUTHORITY_LABELS


PRINCIPLES = [
    ("No citation, no factual claim", "Every material claim must cite a source, or be labeled unverified/estimate/insufficient evidence. Enforced by src/guardrails/citation_validator.py before any brief can be saved."),
    ("Primary sources first", "SEC filings & insider filings outrank earnings materials, which outrank IR/press releases, which outrank news, which outrank social media (never treated as evidence)."),
    ("Separate fact from analysis", "Every brief has visibly distinct Verified Evidence, Bull/Bear Case, Contradictions, Open Questions, and Research Conclusion sections."),
    ("No hallucination", "Nothing in a brief is generated by a language model in V1 — every fact is pulled directly from a provider and cited. See README for the optional, off-by-default narrative-polish hook."),
    ("Recency and freshness", "Every source shows its date and a freshness status (fresh/aging/stale/very stale). Thresholds are user-editable in App Settings."),
    ("Evidence hierarchy on conflict", "When sources disagree, the higher-authority and/or more recent source is weighted, and the conflict is shown, not hidden. See src/guardrails/source_hierarchy.py."),
    ("No price prediction or trade recommendation", "System-generated text is hard-blocked from buy/sell/hold/guaranteed/price-target language. See src/guardrails/language_filters.py."),
    ("No autonomous actions", "This app can research, score, compare, note, and alert. It cannot trade, move money, or take any external action."),
    ("Auditability", "Every material change (ticker added, watchlist edited, thesis updated, brief generated) is logged to audit_logs with a timestamp and payload."),
    ("Cost control", "No browser automation, no LLM calls, and bounded source/excerpt counts per brief. No background jobs — alerts only run when you click the button."),
]


def render(settings: Settings) -> None:
    st.write("These are enforced as application rules, not just prompt instructions.")

    for title, desc in PRINCIPLES:
        with st.expander(title):
            st.write(desc)

    st.divider()
    st.subheader("Source authority hierarchy")
    st.table([{"Rank": r, "Category": label} for r, label in sorted(AUTHORITY_LABELS.items())])

    st.subheader("Banned trade-recommendation language (hard-blocked in generated content)")
    st.code("\n".join(BANNED_PATTERNS), language="text")

    st.divider()
    st.subheader("Guardrail activity")
    with get_connection(settings) as conn:
        blocks = conn.execute(
            "SELECT * FROM audit_logs WHERE event_type = 'guardrail_block' ORDER BY created_at DESC LIMIT 20"
        ).fetchall()
    st.metric("Citation validation blocks (all time)", len(blocks))
    for b in blocks:
        st.caption(f"{b['created_at']} [{b['ticker']}] {b['payload_json']}")
