[theme]
base = "dark"

primaryColor = "#B4B4B4"
backgroundColor = "#212121"
secondaryBackgroundColor = "#2A2A2A"
textColor = "#ECECEC"

linkColor = "#ECECEC"
linkUnderline = false

borderColor = "rgba(255, 255, 255, .08)"
dataframeBorderColor = "rgba(255, 255, 255, .08)"
dataframeHeaderBackgroundColor = "#2A2A2A"

codeTextColor = "#ECECEC"
codeBackgroundColor = "#2A2A2A"

font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap"
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap"

baseFontSize = 15
headingFontWeights = [600, 600, 600, 600, 600, 600]

baseRadius = "small"
buttonRadius = "small"

showWidgetBorder = true
showSidebarBorder = false

[server]
headless = true

[browser]
gatherUsageStats = false
